# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scout_msgs/ScoutRsStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ScoutRsStatus(genpy.Message):
  _md5sum = "e023f9f94b48268948746d41e8f52039"
  _type = "scout_msgs/ScoutRsStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int8 stick_left_h
int8 stick_left_v
int8 stick_right_h
int8 stick_right_v

uint8 swa
uint8 swb
uint8 swc
uint8 swd

uint8 var_a

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','stick_left_h','stick_left_v','stick_right_h','stick_right_v','swa','swb','swc','swd','var_a']
  _slot_types = ['std_msgs/Header','int8','int8','int8','int8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,stick_left_h,stick_left_v,stick_right_h,stick_right_v,swa,swb,swc,swd,var_a

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ScoutRsStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stick_left_h is None:
        self.stick_left_h = 0
      if self.stick_left_v is None:
        self.stick_left_v = 0
      if self.stick_right_h is None:
        self.stick_right_h = 0
      if self.stick_right_v is None:
        self.stick_right_v = 0
      if self.swa is None:
        self.swa = 0
      if self.swb is None:
        self.swb = 0
      if self.swc is None:
        self.swc = 0
      if self.swd is None:
        self.swd = 0
      if self.var_a is None:
        self.var_a = 0
    else:
      self.header = std_msgs.msg.Header()
      self.stick_left_h = 0
      self.stick_left_v = 0
      self.stick_right_h = 0
      self.stick_right_v = 0
      self.swa = 0
      self.swb = 0
      self.swc = 0
      self.swd = 0
      self.var_a = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4b5B().pack(_x.stick_left_h, _x.stick_left_v, _x.stick_right_h, _x.stick_right_v, _x.swa, _x.swb, _x.swc, _x.swd, _x.var_a))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.stick_left_h, _x.stick_left_v, _x.stick_right_h, _x.stick_right_v, _x.swa, _x.swb, _x.swc, _x.swd, _x.var_a,) = _get_struct_4b5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4b5B().pack(_x.stick_left_h, _x.stick_left_v, _x.stick_right_h, _x.stick_right_v, _x.swa, _x.swb, _x.swc, _x.swd, _x.var_a))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.stick_left_h, _x.stick_left_v, _x.stick_right_h, _x.stick_right_v, _x.swa, _x.swb, _x.swc, _x.swd, _x.var_a,) = _get_struct_4b5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4b5B = None
def _get_struct_4b5B():
    global _struct_4b5B
    if _struct_4b5B is None:
        _struct_4b5B = struct.Struct("<4b5B")
    return _struct_4b5B
